from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

def getAddrDockWidget(self, mw):
    ret = QDockWidget(mw)
    sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(ret.sizePolicy().hasHeightForWidth())
    ret.setSizePolicy(sizePolicy)
    ret.setFeatures(QDockWidget.NoDockWidgetFeatures)
    ret.setAllowedAreas(Qt.TopDockWidgetArea)
    ret.setObjectName("addrDockWidget")
    self.dockWidgetContents_2 = QWidget()
    sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.dockWidgetContents_2.sizePolicy().hasHeightForWidth())
    self.dockWidgetContents_2.setSizePolicy(sizePolicy)
    self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
    self.gridLayout = QGridLayout(self.dockWidgetContents_2)
    self.gridLayout.setContentsMargins(11, 11, 11, 11)
    self.gridLayout.setSpacing(6)
    self.gridLayout.setObjectName("gridLayout")
    self.connectButton = QPushButton(self.dockWidgetContents_2)
    self.connectButton.setObjectName("connectButton")
    self.gridLayout.addWidget(self.connectButton, 1, 4, 1, 1)
    self.disconnectButton = QPushButton(self.dockWidgetContents_2)
    self.disconnectButton.setObjectName("disconnectButton")
    self.gridLayout.addWidget(self.disconnectButton, 1, 5, 1, 1)
    self.addrComboBox = QComboBox(self.dockWidgetContents_2)
    sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.addrComboBox.sizePolicy().hasHeightForWidth())
    self.addrComboBox.setSizePolicy(sizePolicy)
    self.addrComboBox.setEditable(True)
    self.addrComboBox.setInsertPolicy(QComboBox.InsertAtTop)
    self.addrComboBox.setObjectName("addrComboBox")
    self.gridLayout.addWidget(self.addrComboBox, 1, 2, 1, 1)
    self.connectOptionButton = QPushButton(self.dockWidgetContents_2)
    self.connectOptionButton.setObjectName("connectOptionButton")
    self.gridLayout.addWidget(self.connectOptionButton, 1, 3, 1, 1)
    ret.setWidget(self.dockWidgetContents_2)
    return ret

