//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovaVSProj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CovalyzerEntities : DbContext
    {
        public CovalyzerEntities()
            : base("name=CovalyzerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Etf> Etf { get; set; }
        public virtual DbSet<MemberMap> MemberMap { get; set; }
        public virtual DbSet<Option> Option { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Security> Security { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockExchange> StockExchange { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<Underlier> Underlier { get; set; }
        public virtual DbSet<Watchlist> Watchlist { get; set; }
    }
}
