//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovaVSProj
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Price
    {
        public int id { get; set; }
        public int security_id { get; set; }
        public byte[] tstamp { get; set; }
        public string bid { get; set; }
        public string ask { get; set; }
        public string last { get; set; }
    
        public virtual Security Security { get; set; }
    }
}
