//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovaVSProj
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Stock
    {
        public int id { get; set; }
        public int security_id { get; set; }
        public int exdividend_dates_id { get; set; }
        public int earningcall_dates_id { get; set; }
        public string name { get; set; }
    
        public virtual EarningcallsDate EarningcallsDate { get; set; }
        public virtual ExDividendDate ExDividendDate { get; set; }
        public virtual Security Security { get; set; }
    }
}
